---
title: "Covid-19 análise espaço-temporal."
author: "Lucas Rabelo"
output:
  pdf_document:
    toc: no
    toc_depth: '6'
    number_sections: no
    keep_tex: yes
    citation_package: natbib
    pandoc_args: --listings
    includes: null
  word_document:
    toc: no
    toc_depth: '6'
geometry: margin=1in
fontsize: 12pt
linestretch: 1.5
documentclass: report
---

## Introdução {.tabset .tabset-fade .tabset-pills}

 No final de 2019, o estado de contágio pela Covid-19 já era considerado como epidêmico na cidade de Wuhan na China $\!\!^1$, apesar da dificuldade de identificar a origem do vírus, é possível que tanto pangolim como o morcego tenham sido hospedeiros iniciais, visto que tanto o SARS quanto o MERS geralmente passam por hospedeiros intermediários $\!\!^2$. Apesar de anteriormente diversos orgãos públicos recomendarem cautela em relação a Covid-19, em 12 de março de 2020 o estado de pandemia foi reconhecido pela Organização Mundial da Saúde (OMS) $\!\!^3$.  

 Devido a presença de infectados pela Covid-19 na maioria dos países do globo, é de suma importância que sejam realizados estudos sobre o caráter espaço-temporal da pandemia, identificando fatores como as políticas de contenção ao contágio adotadas pelos países de acordo com o tempo e a aceleração do crescimento de infectados em cada nação. Ao traçar um perfil sobre o comportamento espaço-temporal da Covid-19, estudos como esse poderão ser analisados para lidar com possíveis pandemias causadas por vírus que apresentem características similares a Sars-CoV-2.
 
 O objetivo deste trabalho será portanto traçar um perfil sobre o comportamento espacial da pandemia causada pelo vírus da Covid-19 ao utilizar de técnicas estatísticas para quantificação da dependência espacial como o cálculo do índice de Moran global e local $\!\!^4$, bem como analisar as políticas adotadas por cada país e o comportamento da pandemia ao longo do tempo.
 
## Metodologia

 Para implementação das técnicas estatísticas, cálculo da dependência espacial e uso do banco de dados foi utilizado o software R (versão 4.0.3), o qual contém a biblioteca COVID19 implementada pela *COVID-19 Data Hub* $\!\!^5$, responsável por providenciar um banco de dados unificado e constantemente atualizado, com início em Fevereiro de 2020. O banco de dados disponibilizado pela *COVID-19 Data Hub* além de conter diversas fontes de informação diferentes para todos os países em que foi possível a obtenção de dados, também providencia as medidas políticas adotadas de acordo com o tempo durante a pandemia.
 
 Os números acumulados e mensais de mortes, recuperados e casos confirmados são disponibilizados pelo banco de dados, juntamente com a quantidade de habitantes de cada país, portanto para melhor capturar o impacto do Covid-19 em cada localidade as três variáveis foram calculadas de acordo com a razão pelo número de habitantes.

#### Índice de Moran
 
 Para avaliar a dependência espacial foi utilizado o método knn para ligar os polígnos e criar a matriz de vizinhança normalizada por linha para que fossem calculados o Índice de Moran global e o local, o índice global é o método tradicionalmente usado e condensa a dependência espacial em apenas um número $\!\!^6$, no entanto o uso do indicador local de associação espacial (LISA) utilizado para identificar padrões espaciais, se faz útil pois de acordo com Maia, Gomes e Almeida (2018, p.930) enquanto o índice de Moran global pode sugerir que haja baixa correlação espacial nos dados, os valores do LISA podem identificar sub-regiões geográficas em que o agrupamento (*clustering*) negativo ou positivo ocorram $\!\!^7$.
 
 Como valores dentre 0 e 1 indicam correlação direta e positiva e negativos até -1 correlação inversa $\!\!^4$, por estarmos interessados na presença de dependência espacial positiva os testes de hipótese foram construídos com nível de significância de 95%, seguindo a premissa de que a hipótese alternativa corresponde a um índice maior que zero, e a hipótese nula é de independência espacial, ou seja Ho=0 e H1>0. A validação do índice foi feita utilizando 10.000 simulações em um teste de permutações aleatórias.
 
## Resultados

 A partir do mês de Abril, o número acumulado de mortes por habitante apresentou uma correlação espacial no índice de Moran global (IM>0,50; P-valor<0,05) que se manteve em um alto patamar de correlação até o mês de Julho. Referente ao índice de Moran calculado para o número mensal de mortes por habitante (ou seja sem o efeito da sazionalidade), no mês de Abril o índice de Moran global (IM=0,72; P-valor<0,05) apresentou um alto patamar de dependência.
 
 Os índices locais de Moran para o número acumulado de mortes por habitante e para a quantidade mensal, dão um indicativo de uma grande dependência espacial entre a parte ocidental da Europa, América do Norte e América do Sul, havendo poucas diferenças entre os mapas de correlação local ao longo dos meses. Até o mês de Julho referente ao número cumulativo de morte por quantidade de casos o Iêmen foi o país com maior número de mortos por infectados, chegando a um falecimento de 29% dos contagiados pelo Covid-19.
 
## Discussão

 A partir do mês de Maio houve uma abrupta aceleração no crescimento da quantidade de casos acumulados por habitante em todos os continentes, sendo este mês o pico de contágio no primeiro semestre, se mantendo em um alto patamar até o mês de Julho. No entanto o crescimento do número de casos acumulados já é visível no mês de Abril em diversos continentes como na América do Norte, América do Sul, Ásia e Europa continente que apresentou dependência espacial no número cumulativo e mensal de mortes por habitantes já no mês de Abril apresentava uma dependência espacial local. 

## Conclusão

 Portanto é de se concluir que há uma dependência espacial no número de mortes cumulativo por habitantes infectados pela Covid-19, sendo esta mais notável nos países da parte ocidental da Europa e na América do Sul, existe portanto a necessidade de se investigar o motivo de tal dependência espacial, presente também sem o efeito da sazionalidade ao se analizar o número mensal mortes por habitantes.

## Referências

[1] - https://reader.elsevier.com/reader/sd/pii/S2090123220300540?token=26B4D22A444963A79BDEF6C0D5D6B7DBAB6E417B72741E9408077164DFE98DD3C60085E40FB8A46964B454ECB0981D81

[2] - https://reader.elsevier.com/reader/sd/pii/S0960982220303602?token=DDACE18C1AEF3D5006049D4C47E460D652C20143E76F940DC4A8391256E205355A5219746EA07D1536C391E71CE6CDE4

[3] - https://www.euro.who.int/en/health-topics/health-emergencies/coronavirus-covid-19/news/news/2020/3/who-announces-covid-19-outbreak-a-pandemic

[4] - http://www.sinaldetransito.com.br/artigos/espacial.pdf

[5] - Guidotti, E., Ardia, D., (2020), "COVID-19 Data Hub", Journal of Open Source Software 5(51):2376, doi: 10.21105/joss.02376.

[6] - http://www2.ime.unicamp.br/sinape/sites/default/files/Resumo%20expandido%20SINAPE.pdf

[7] - SPATIAL STUDY OF INCIDENCE RATES OF OCCUPATIONAL ACCIDENTS IN BRAZIL FROM 2002 TO 2012
