---
title: "Applying Spatio-temporal Scan Statistics and Spatial Autocorrelation Statistics to identify Covid-19 clusters in the world."
author: "Lucas Rabelo"
output:
  pdf_document:
    toc: no
    toc_depth: '6'
    number_sections: no
    keep_tex: yes
    citation_package: natbib
    pandoc_args: --listings
    includes: null
  word_document:
    toc: no
    toc_depth: '6'
geometry: margin=1in
fontsize: 12pt
linestretch: 1.5
documentclass: report
---

## Introduction {.tabset .tabset-fade .tabset-pills}
   
 At the end of 2019, the situation of infections by Covid-19 *(Sars-Cov-2)* was already being considered an epidemic in the city of Wuhan in China $\!\!^1$, although it was difficult at first to identify the virus' origin, it's known that the Severe Acute Respiratory Syndrome *(SARS)* and the Middle East Respiratory Syndrome *(MERS)* usually need intermediate hosts $\!\!^2$, there is a possibility that bats and pangolins were the first carriers. After several public organizations called for caution relating to Covid-19, on March 11 of 2020 the pandemic state was recognized by the World Health Organization *(WHO)* $\!\!^3$.
 
 With the whole world being affected by the pandemic, it's a matter of great importance that studies about the spatio-temporal aspects of the Covid-19 pandemic should be conducted, the main goal of this paper is to present methods used to identify spatial and spatio-temporal dependence in the number of infections and deaths caused by Sars-Cov-2 in different countries according to time in 2020, so these techniques may be used in future or hypothetical situations where is necessary to investigate the behavior of a pathogen agent in space and time.
 
 The spatial method was calculated by using the Global Moran's I and the Local Moran's I $\!\!^4$, which is also known as a LISA statistic (Local Indicator of Spatial Association), both being used as indicators of spatial association. Spatio-temporal association was evaluated by computing a spatio-temporal Poisson scan statistic, proposed by Kulldorff $\!\!^5$ to identify emerging or "alive" *clusters* in space and time.
 
## Methods
 
 The statistical software R (Version 4.0.3) was used to calculate the spatial and the spatio-temporal association, the Covid-19 database used in the study is also available in R, in a package called "COVID19" built by the *COVID-19 Data Hub* $\!\!^6$, the database begins in January 2020 and is constantly updated, it also gathers data from various sources of information for all countries in which it was possible to obtain data. The database provides data about political measures adopted by each country during the pandemic, even though that information is not available for all countries included, which is one of the limitations of the database, that lack of data is also be seen in variables such as the number of recovered cases, where China for instance had no recovered cases during the analysis' period of time, since the reason for this was not explicit in the website of *COVID-19 Data Hub*, this paper supposes it was not possible to access data for countries which the information was lacking in the unified database.

 The cumulative number of deaths, infections and recovered cases is given by the database, but since these numbers are only available in its daily cumulative form, it was necessary to calculate monthly quantities for each one of the variables in the period of time considered in this paper between January and December 2020. The population of each country is also available in the database, so in order to better understand the spatial and the spatio-temporal effects of Covid-19 in each location, it was necessary to calculate the ratio between the number of infections, the number of recovered cases and the quantity of deaths in the population.

#### Moran's I
 
 To evaluate spatial association during the first year of the pandemic, a knn method was used to create spatial polygons and to build spatial weight matrices, which are necessary to calculate the Global Moran's I and the *LISA*. The Global Moran's I is widely used and gathers all spatial dependence in one value $\!\!^7$, while the use of the Local Moran's I is important to identify patterns of spatial association, hence the *LISA* should be used with the Global Moran's I, as it's stated by Maia, Gomes and Almeida (2019, p.930) "while the global Moran's I may suggest, in general, that there is little spatial autocorrelation in the data, LISA values can identify smaller geographic areas where positive or negative clustering occurs." $\!\!^8$.
 
 The Global Moran's I is calculated as shown in **(Equation 1)**, with $w$ as the spatial weight matrix, $x$ as the values of the studied variable, $n$ as the number of identified polygons and $\overline x$ as the mean or average:

**Equation 1**

$$Im = \frac{n\sum_{i=1}^{n}\sum_{j=1}^{n}(x_{i}-\overline{x})(x_{j}-\overline{x})w_{ij}}{W\sum_{i=1}^{n}(x_{i}-\overline{x})^2}$$
 Where W is defined by the following equation:
 $$W=\sum_{i=1}^{n}\sum_{j=1}^{n}w_{ij}$$
 

 The values range from -1 to 1, with the 0 value indicating an absence of spatial autocorrelation, positive values are indicators of positive spatial association, while negative values mean there is an inverse association, since this work seeks to find positive spatial association, the hypothesis tests were built within a 95% confidence level, so that the alternative hypothesis (H1) corresponds to an index higher than zero and the null hypothesis (Ho) to a lack of spatial association, both of which can be written mathematically as Ho=0 and H1>0. The monthly quantities were important to avoid problems of non-stationarity when computing the Global Moran's I, according to Cardoso (2007, p.3, translated from portuguese) "The index loses its validity when calculated for non-stationary data.", in order to validate the index 10,000 simulations were computed in a test of random permutations (*Monte-Carlo*) $\!\!^9$.
 
 Whereas the Local Moran's I (*LISA*) is calculated by the following equation (**Equation 2**):

**Equation 2**
 $$I(i) = \frac{x_{i}-\overline x}{s^{2}_{i}}\sum_{j=1}^{n}w_{ij}(x_{j}-\overline{x}), i=1,...,n, j\neq i$$
 Where $s^{2}_{i}$ is the variance of the studied variable $x_{i}$:
  $$s^{2}(i) = \frac{\sum_{j=1}^{n}(x_{j}-\overline x)^{2}}{n-1}, i=1,...,n, j\neq i$$
  
  Maps for the Local Moran's I, *Boxmaps* and Global Moran's I tables, were built for variables (number of cases and deaths) which achieved a global index IM>0.50 at least in one month during 2020. Boxmaps are cartographic representations of the Moran scatter plot, in which according to Seffrin, Araujo e Bazzi (2018,p.28) the HH means that the identified locations have high index values and are close to other areas of high value, the LL value means that areas identified with low values are surrounded by areas with low values, the LH value represents areas with a low value surrounded by other areas with high values, while HL is the opposite, they are regions with high values close to locations with low values.
  
#### The Poisson Scan Statistc

  The prospective scan statistic proposed by Kulldorff $\!\!^5$ was chosen to identify emerging spatio-temporal *clusters* in the cumulative number of cases for each month, to apply the technique it was considered that the data follows a Poisson distribution. The purely spatial scan statistic creates a wide variety of circular windows in different locations throughout the map, each one with a specific group of neighboring areas, all of these circular windows are also flexible in their two dimensions, size and locality, and may or not contain a *cluster* of events. A scan statistic is defined as the likelihood ratio over all possible circles and when maximized identifies the one which constitutes the most likely *cluster*, the *p*-value is obtained through the *Monte-Carlo* hypothesis test.
 
 In opposition to the purely spatial scan statistic, the spatio-temporal scan statistic creates cylindrical windows in three dimensions, where the height is a representation of time, the cylinders are flexible in their circular bases and initial dates, hence only "alive" *clusters*, the ones which cylinders achieved the end of the study period are considered, the maximum likelihood ratio tests are conducted the same way as they are in the purely spatial scan statistic.
 
 Spatio-temporal scan statistics are useful to identify emerging *clusters*, since purely spatial scan statistics have a few limitations as it's pointed by Kulldorff (2001, p. 66), there is little power to detect emerging *clusters* when conducting a purely spatial analysis for a long period of time, therefore the solution would be to use a spatio-temporal scan statistic. 

## Results

 When calculated for the number of deaths per inhabitant in each country **(Table 1)**, the highest index of global spatial association was achieved in April (IM=0.72; P-value<0.05), other months identified with high Global Moran's I values were November (IM=0.69; P-value<0.05) and December (IM=0.70; P-value<0.05). Whereas when computed for the number of infections per inhabitant caused by Covid-19 **(Table 2)**, the highest values for the Global Moran's I were found in October (IM=0.60; P-value<0.05), November (IM=0.67; P-value<0.05) and December (IM=0.58; P-value<0.05).
 
 Considering the number of deaths per inhabitant, when identifying local spatial autocorrelation with the Local Moran's I  **(Picture 1)** after April, month with the highest Global Moran's I, spatial dependence was strong in Europe, South America and North America, with little difference in maps throughout the year. For the number of infections per inhabitant, after October, which was the first month with a high global dependence, local association was strong in Europe until the end of the year **(Picture 2)**.
 
 The Spatio-Temporal Scan statistic was only computed for the number of cumulative cases during the pandemic, the method to calculate spatio-temporal *clusters* showed itself to be way more computer intensive than the calculation of the Global Moran's I and the *LISA*. But the Spatio-Temporal Scan statistic also was efficient to identify emerging *clusters* in space and time, with most of the locations in October and November also identified in the Local Moran's I for these months.
 
## Discussion
  
  In April global cases of Covid-19 reached 1 million, in the same month the world also reached 3 million cases $\!\!^1\!^0$, with an exponential growth in the number of infections, the Global Moran's I was also very high for the number of deaths per inhabitant, while local spatial association was strong only in Europe, the boxmap **(Picture 3)** shows that all areas identified with local dependence for the number of deaths per inhabitant were either HH (High-High) clusters in April or HL (High-Low) clusters after April, which means that generally locations with a high number of deaths were close to other areas that also had a high number of deaths.


## Conclusion
 
## Referências

[1] - Muhammad Adnan Shereen, Suliman Khan, Abeer Kazmi, Nadia Bashir, Rabeea Siddique, COVID-19 infection: Origin, transmission, and characteristics of human coronaviruses, Journal of Advanced Research, Volume 24, 2020, Pages 91-98, ISSN 2090-1232, https://doi.org/10.1016/j.jare.2020.03.005.

[2] - Tao Zhang, Qunfu Wu, Zhigang Zhang, Probable Pangolin Origin of SARS-CoV-2 Associated with the COVID-19 Outbreak, Current Biology, Volume 30, Issue 7, 2020, Pages 1346-1351.e2, ISSN 0960-9822, https://doi.org/10.1016/j.cub.2020.03.022.

[3] - WHO announces COVID-19 outbreak a pandemic. World Health Organization Regional Office for Europe. [S.l.]. Publicado em: 12/03/2020. <https://www.euro.who.int/en/health-topics/health-emergencies/coronavirus-covid-19/news/news/2020/3/who-announces-covid-19-outbreak-a-pandemic>. Acesso em: 24/11/2020.

[4] -CARDOSO, Carlos Eduardo de Paiva. Dependência Espacial, Setores Censitários, Zonas OD, Distritos, Sub Prefeituras e etc. [S.l]. Publicado em: 06/09/2007. <http://www.sinaldetransito.com.br/artigos/espacial.pdf>. Acesso em: 24/11/2020.

[5] - Kulldorff, M. (2001). Prospective time periodic geographical disease surveillance using a scan statistic. Journal of the Royal Statistical Society: Series A (Statistics in Society), 164(1), 61–72. doi:10.1111/1467-985x.00186 

[6] - Guidotti, E., Ardia, D., (2020), “COVID-19 Data Hub”, Journal of Open Source Software 5(51):2376, doi: 10.21105/joss.02376.

[7] - BRAGA, Altemir da Silva.*et al*. Estudo de Dependência Espacial utilizando Análise de Dados de Área Aplicada na Mesorregião Metropolitana de Belo Horizonte por meio do Indicador Econômico PIB. 19ª SINAPE.  [S.l.]. 2010,  Disponível em: <http://www2.ime.unicamp.br/sinape/sites/default/files/Resumo%20expandido%20SINAPE.pdf>. Acesso em: 24/11/2020.

[8] - MAIA, André Luis Santiago; GOMES, Gecynalda Soares da Silva; ALMEIDA, Isabelle Galdino de. SPATIAL STUDY OF INCIDENCE RATES OF OCCUPATIONAL ACCIDENTS IN BRAZIL FROM 2002 TO 2012. REVISTA BRASILEIRA DE BIOMETRIA, [S.l.], v. 36, n. 4, p. 927-941, dec. 2018. ISSN 1983-0823. Available at: <http://www.biometria.ufla.br/index.php/BBJ/article/view/322>. Date accessed: 24 nov. 2020. doi: https://doi.org/10.28951/rbb.v36i4.322.    

[9] - SEFFRIN, R.; ARAUJO, E. C.; BAZZI, C. L.. Análise espacial de área aplicada a produtividade de soja na região oeste do Paraná utilizando o software R. R. bras. Geom., Curitiba, v. 6, n. 1, p. 23-43, jan/mar.2018. Disponível em: <https://periodicos.utfpr.edu.br/rbgeo/article/view/5912>. Acesso em: 24/11/2020.DOI: 10.3895/rbgeo.v6n1.5912

[10] - Brodeur, *et al*. (2020): A Literature Review of the Economics of COVID-19, GLO Discussion Paper, No. 601, GlobalLabor Organization (GLO), Essen. Available at: http://hdl.handle.net/10419/222316
